name: Build Windows EXE

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Compile Java
        run: |
          cd src
          javac app/Main.java

      - name: Create JAR
        run:
          |
          jar -cfe Game.jar app.Main -C src . -C resources .

      - name: Create EXE with jpackage
        run: |
          mkdir dist
          move Game.jar dist/
          jpackage --input dist --name Game --main-jar Game.jar --main-class app.Main --type exe --dest output

#      - name: Create EXE with jpackage
#        run: |
#          jpackage --input . --name Game --main-jar Game.jar --main-class app.Main --type exe
  #--icon /home/iasonas/IdeaProjects/Victims2/Victims2_EXE.png \
  #--app-version 2.45 \
  #--java-options "-Xmx512m"

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: GameEXE
          path: Game
